[build]
  publish = "frontend/build"
  command = "cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  # Production environment variables
  REACT_APP_API_URL = "https://emailservice-production-ec26.up.railway.app/api"
  REACT_APP_APP_NAME = "E-Cell Email Service"
  REACT_APP_VERSION = "1.0.0"
  REACT_APP_ENVIRONMENT = "production"

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:;"
